server:
  port: 7200

spring:
  application:
    name: idoss-web
  profiles:
      active: ${SPRING_PROFILES_ACTIVE}
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /
      suffix: .jsp


logging:
  file: ./logs/idoss-web.log
  level:
    com.sprucetec: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %clr(%logger){cyan} %clr(%msg%n){green}"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
