dubbo:
  application:
    #应用定义了提供方应用信息，用于计算依赖关系;
    name: ${spring.application.name}
    #应用所属者
    owner: ser
    #应用所属组织
    organization: se-group
  #使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  registry:
    #注册中心id
    id: zookeeper-registry
    #注册中心协议
    protocol: zookeeper
    #注册中心地址
    address: 127.0.0.1:2181
  #dubbo协议在20880端口暴露服务
  protocol:
    #协议名称
    name: dubbo
    #协议端口
    port: 20880
    #协议访问log
    accesslog: logs/dubbo-web.log
  provider:
    #重试次数
    retries: 5
    #超时时间
    timeout: 3000
  #注册监控中心
#  monitor:
#    protocol: registry

swagger:
  enabled: true
